name: Discord Notification

on:
  push:
    branches:
      - main
      - master

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Embed
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        run: |
          curl \
          -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds":[
              {
                "title":"✅ New Commit",
                "color":5763719,
                "fields":[
                  {
                    "name":"📦 Repository",
                    "value":"${{ github.repository }}",
                    "inline":true
                  },
                  {
                    "name":"🌿 Branch",
                    "value":"${{ github.ref_name }}",
                    "inline":true
                  },
                  {
                    "name":"👤 Author",
                    "value":"${{ github.actor }}",
                    "inline":true
                  },
                  {
                    "name":"💬 Commit",
                    "value":"${{ github.event.head_commit.message }}"
                  }
                ],
                "url":"https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
                "footer":{
                  "text":"GitHub Actions"
                },
                "timestamp":"${{ github.event.head_commit.timestamp }}"
              }
            ]
          }' \
          "$WEBHOOK"